# Site settings
title: Amla Rathore's CV
description: Amla Rathore's CV
favicon: /assets/img/avatar.jpg
baseurl: https://amlarathore.github.io
url: https://amlarathore.github.io
rss_url: /pages/atom.xml
google_analytics: UA-80108133-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Amla Rathore
  title: Media Manager
  address: Singapore
  email: amla.rathore@yahoo.com
  link:
  weibo:
  github:
  linkedin: amlarathore
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work1:
      company: IH Digital
      location: Singapore, Singapore
      title: Media Manager
      started: 2016
      duration: (July 2016 - Present)
      description: Responsible for planning and buying of digital media and activation of digital campaigns on different platforms. <br>
                   Timely optimization of campaigns to improve ROI and help client achieve defined objectives. <br>
                   Generating insightful reports and making recommendation based on past campaigns performance. <br>
                   Working closely with the in-house content team and liaising with clients to get approval of campaigns and content, understanding their changing needs and adapting our approach to social media management for them accordingly.

    - work2:
      company: Media.net
      location: Mumbai, India
      title: Associate Manager
      started: 2015
      duration: (Jan 2015 - May 2016)
      description: Managing yearly revenue of around $ 20M. Responsible for campaign management, dataanalysis and account optimization for big publishers. <br>
                   Design, build and managed team of 20 research analysts and lead the monetizationefforts for both text and display ads. <br>
                   Strategizing optimization process to help team achieve revenue targets and maximize ROI for publishers. <br>
                   Responsible for gathering intelligence on current trends and issues within various verticals and disseminating these insights to the team. <br>
                   Proactively work with Business Development team to find digital channels that will constantly improve upon marketing ROI and drive product and services conversion <br>
    - work3:
      company: Media.net
      location: Mumbai, India
      title: Module Lead
      started: 2012
      duration: (2012 - 2015)
      description: Acted as a bridge between sales and account management team to achieve target. <br>
                   Liaising with the Business Development Specialists to facilitate maximization of revenue and to ensure smooth functioning of the department. <br>

    - work4:
      company: Media.net
      location: Mumbai, India
      title: Senior Research Analyst
      started: 2011
      duration: (2011 - 2012)
      description: Mentoring the new employees in the team and assisting them with work related queries. <br>
                   Optimizing Domain Names and investigating web sites and conducting research & analysis for identifying concepts of domain names. <br>
                   Monitoring and enforcement of acceptable usage policies in cases of system abuse, illegal usage, misrepresentation etc.<br>
    - work5:
      company: Media.net
      location: Mumbai, India
      title: Research Analyst
      started: 2007
      duration: (2007 - 2011)
      description: Optimizing Domain Names and investigating web sites and conducting research & analysis for identifying concepts of domain names. <br>
                   Checking content, quality and accuracy of each concept. <br>
                   Consistently monitor domain names as per customer feedback and satisfaction.<br>
  educationHistory:
    - education1:
      organization: Medicaps Institute of Science and Management
      location: Indore, India
      degree: Bachelor
      major: Engineering
      started: 2003
      duration: (2003 - 2007)
      description: Studied electricals and electronics engineering.     <br>
  frameworks:
    - framework1:
      name: Team Management
    - framework2:
      name: Lead Generation
    - framework2:
      name: New Hire Training
    - framework2:
      name: Market Research
  programmingSkills:
    - skill1:
      name: Website Monetization
      percentage: 100%
    - skill2:
      name: Campaign Management
      percentage: 80%
    - skill3:
      name: Data Analysis
      percentage: 100%
    - skill4:
      name: Social Media Planning
      percentage: 80%
    - skill4:
      name: Social Media Buying
      percentage: 80%
    - skill5:
      name: Campaign Setups
      percentage: 100%
    - skill5:
      name: Google Adwords
      percentage: 100%
  databases:
   - database1:
     name: Google AdWords Fundamentals &nbsp;&nbsp;&nbsp;<a href="https://www.google.com/partners/#i_profile;idtf=115139821576005682181;">Verify</a>
   - database1:
     name: Google Video Advertising &nbsp;&nbsp;&nbsp;<a href="https://www.google.com/partners/#i_profile;idtf=115139821576005682181;">Verify</a>
